version: '2'

services:
  bokeh:
    restart: always
    build:
      context: .
      args:
        BOKEH_PREFIX: /mofs
    image: discover-mofs:master
    command: ["/opt/serve-app.sh"]
    environment:
      PYTHONPATH: '/project'
      SHELL: '/bin/bash'

    volumes:
     - './data:/project/discover-mofs/data'
    ports:
      - '3247:5006'
